### PR TITLE
Don't request more IRC messages until the last request is complete.

### LINKED ISSUE #45: IRC logs can load duplicate records
When the server takes +3 seconds to respond to a request, multiple requests are sent to the server. Because the IRC log refresh logic is basic both these requests return the same results, loading duplicate data in the view.

The client should not send another request until the previous one has returned. The client should also display a message if the previous request failed.

### PR DESCRIPTION
**Pull request by utkarshkukreti**
Fixes #45

### CODE REVIEW

**Comment by jordanbyron** [comment]
I love the simplicity of this fix, but worry that once a request times out the page will never attempt to refresh again.

Ideally if the getJSON request fails, it would then reset the interval and display a message to the user alerting them the connection to the server has been lost. I'd use the flash message partial we have to notify the user of problems.

If that gets difficult feel free to throw around other options. Sorry for closing both pull requests. I do appreciate your help, and this one is really close to being ready.

Thanks!

Jordan

**Comment by utkarshkukreti** [comment]
`$.getJSON` doesn't have any error handler, so I switched the method to use `$.ajax` instead, and made it add an error message as `#flash > .error`.

Let me know if this is fine!

https://github.com/utkarshkukreti/university-web/commit/0b38bfce6e34d1c2214d5c40099b5ae40fc81719

**Comment by jordanbyron** [comment]
That looks so much better. Only one more change:

Hook into the complete callback to set the timeout. That way regardless of the success of the transaction, the page will continue to refresh. Once that is in place shoot over the pull request and I will happily merge it.

Thanks for all your work!

Jordan

**Comment by utkarshkukreti** [comment]
Let me know if this is fine https://github.com/utkarshkukreti/university-web/commit/8adefd0ad21131c3677a2f095e87842e9738759f

**Comment by jordanbyron** [comment]
The code appears to be correct, but did you actually try running it? When I test it locally the javascript throws an unhandled exception when I turn off the server.

Are you seeing the same thing?

**Comment by utkarshkukreti** [comment]
I did try it, but I tested with sending 500 errors, not shutting down the server, which seemed to work fine.

It looks like the error callback isn't called when you turn off the server, instead data is set to null. Could you verify that? I'll commit and update to make sure that if data is not an array, fire the error callback.

**Comment by jordanbyron** [comment]
> It looks like the error callback isn't called when you turn off the server, instead data is set to null. Could you verify that?

That is exactly what I am seeing.

**Comment by utkarshkukreti** [comment]
Please try it out with my latest commit.

**Comment by jordanbyron** [comment]
Those changes worked awesome. All of that javascript at the top of the file bothered me so I moved it into a dedicated file. If you want you can see what I did in this commit: 6ad5f511d964e59d2092012a361937ec4ea7af69

Thanks again for all your work!

Jordan

**Pull request merged**
