### PR TITLE
Submission hint

### PR DESCRIPTION
**Pull request by madebydna**
Added some jquery popup hints to the submission status in the progress report table. The hints display the abbreviated description of the submissions.

I personally find it useful as a mentor to see at a glance what everyone is working on. Not sure if others would find this useful too. On the downside, the many popups might prove to be annoying.

### CODE REVIEW

**Comment by jordanbyron** [comment]
Hey Andrea,

Thanks for working on this feature. There are a few things I was hoping to you could fix. 
- Restore HAML to 3.1.2 in Gemfile.lock. This commit (ce0f67cbd53152c7700341bec8a54797cf82b5a1) should be excluded entirely.
- Rather then use the really annoying jquery popup tooltips, just use the `title` attribute on the links. That will be way less intrusive but still proved the information.

**Comment by madebydna** [comment]
I made the changes you requested.

I also noticed that the jquery version is wrong on `layouts/user_sessions.html.haml`, which makes the infield labels not work on the login page. I updated that to the correct version.

**Comment by jordanbyron** [comment]
Hi Andrea,

Thanks for making those changes. It looks like your fork has fallen behind the main project. Can you pull in the latest changes and include them in your pull request? Right now when I try to merge this pull request there are conflicts.

Also, the code formatting of [submission_status_link](https://github.com/madebydna/university-web/blob/34a24566297d2c45ab311874de264e7b4f42347b/app/helpers/courses/assignments/submissions_helper.rb) is a little rough. Can you try to clean it up so it reads better?

**Comment by jordanbyron** [comment]
Hey Andrea,

Do you want to keep working on this? Or should we close this request up and you can start from scratch?

Let me know,

Jordan

**Comment by madebydna** [comment]
Yeah, I was thinking about this the other day. I'd like to do it before the new course rolls around, but I think it might be better if I just started from scratch, so feel free to close this pull request. 

I will just get up to date with it the newest version of master and start afresh.

Thanks,

Andrea

**Pull request closed without merging**
