### PR TITLE
Properly format actions in IRC messages, fixes #30.

### LINKED ISSUE #30: IRC Logs don't display actions correctly
If "ella" types the following into an IRC channel:

> /me enjoys a martini

the IRC logs show

> ella: ACTION enjoys a martini

They should show

> ella enjoys a martini

### PR DESCRIPTION
**Pull request by utkarshkukreti**

### CODE REVIEW

**Comment by jordanbyron** [comment]
Hi Utkarsh,

I think we can clean this up a bit. Why don't we add an `action` bit to the Chat::Message model which is set to true when the message body matches that regex. We can create a before_create hook that does that check and strips the action text from the body.

That change would simplify the view and make the code a little more DRY. If you have any questions let me know.

Thanks!

Jordan

**Comment by utkarshkukreti** [comment]
That would be better, but then you'll have to run it once on all the existing messages. I'll send in another request if you're fine with that :)

**Comment by jordanbyron** [comment]
Ah yes, I forgot to add that caveat. You'll need to create a rake task to modify the existing records.

**Comment by utkarshkukreti** [comment]
I added the field, before_create hook, and a rake task. Let me know what you think - https://github.com/utkarshkukreti/university-web/commits/issue-30

**Comment by jordanbyron** [comment]
Merged and deployed. Thanks for your help getting this fixed!

**Pull request merged**
