### PR TITLE
Adding github repositories to users profile

### PR DESCRIPTION
**Pull request by pellegrino**
As my s7-e4 assignment, i listed, at users profile, every public repository he has. 
The discussion about it can be seen in: http://university.rubymendicant.com/courses/11/assignments/49/submissions/702

Here is a [screenshot](http://dl.dropbox.com/u/300888/github-repositories_user_profile.png) about the new user profile page i've implemented

### CODE REVIEW

**Comment by jordanbyron** [comment]
Hey Vitor!

Thanks for working on this really neat feature. I've got your code running on my local machine and there are a few very minor things I was hoping you could change:
1. Sort repositories by last commit, rather than age. This is how github does it and I think that makes the most sense.
2. Paginate the results at 10 per page. Ideally that would utilize ajax pagination to avoid refreshing the entire page.
3. There is a ton of space between each repo. I think we can tighten that up a bit so more are visible above the fold.
4. Rather than using the words 'Watchers' and 'Forks', let's mimic github by using icons. I've uploaded a set of free icons we can use which look similar to githubs. You can download them here: http://dl.dropbox.com/u/351364/github%20icons.zip
5. If we are going to highlight the entire row on hover, then I'd expect the entire row to be clickable, much like the directory.

Please let me know if you have any questions. You've done an outstanding job so far and I look forward to getting these changes merged into university-web.

Jordan

**Comment by pellegrino** [comment]
Hey Jordan!

I have only one question, about the pagination. I've seen kids using much [endless scrolling](http://pedromtavares.wordpress.com/2011/05/08/endless-page-scrolling-with-rails-3-and-jquery/) these days, pretty much like twitter and a lot of other sites are using. I think it could also be used in this situation. 

Well, right now i'm getting my personal project in an accepted to be able to make myself a RMU Alumni :) As soon as RMU ends, i will work at these features. 

I think i can work through this list during this week. 

Thanks once more Jordan!

**Comment by pellegrino** [comment]
Jordan,

i've just seen that github's api doesn't support ordering of the Repos API. I had to sort the results at the user class, what would make paginating this results a little bit "hackish". Do you think its worth doing right now? Have another idea on how to do this?

I was wondering maybe we could get the other issues merged and open up another one to address only the pagination. What do you think about that? I will work on item 3 and 4 right now. :)

http://support.github.com/discussions/api/312-repos-api

**Comment by pellegrino** [comment]
Done. The only thing that is missing is the Pagination issue. Let me know what do you think about this. :)

Thanks!

**Comment by jordanbyron** [comment]
Hi Vitor,

I've made a few cosmetic changes to your code, but with the changes you made I was able to merge this feature in. If you'd like to explore endless scrolling just create a ticket for the feature on Pivotal Tracker https://www.pivotaltracker.com/projects/101484 and assign it to yourself.

Thanks again!

Jordan

**Comment by pellegrino** [comment]
That is good news!

Perfect, i will explore something along those lines. The problem is that
github api doesn't yet support results ordering, so we will have to paginate
it at the client side. As it would take longer to develop this than simply
adding a Well Paginate, i decided to delay this a little bit.

I'll check pivotal later on!

Thanks!

Vitor Pellegrino
http://vp.blog.br

**Pull request merged**
