### PR TITLE
new login logo without letters nor circle

### PR DESCRIPTION
**Pull request by fguillen**
I couldn't check it since I have a problem trying to install the `pg` gem dependency.

Please revise before deploy.

### CODE REVIEW

**Comment by jordanbyron** [comment]
Hi Fernando,

I appreciate that you've attempted to fix this problem, but since you don't have the project up and running there are a few issues. I've taken a screenshot so you can see what I am talking about: http://i.imgur.com/Bc9w5.png

The logo has a white box around it and is a bit too small now. As a general rule of thumb, doing the "guess and check" method isn't great when sending over pull requests. Just think in terms of code: Would you send a pull request including code that you haven't run or tested? I would hope not. Same concept applies here.

Now for this feature you don't _need_ the pg gem to see if this fix works. If you still are having trouble and can't get the project up and running let me know. 

Jordan

**Comment by fguillen** [comment]
I completely agree.. I was in a hurry but you are right: is not good idea to pull a request without testing it.

I have to leave the office now. I'll do it tomorrow.

In the mean time if some one has the 'transparent' version of the 'old' logo it would be helpful. If not, I think I can build it from the one that was sent to me.

**Comment by pellegrino** [comment]
Hey folks, i don't know if this discussion if well suited here. If that isn't the correct place, let me know and i'll forward accordingly. 

Well, i was with this thing back at my head wondering if Mendicant University should keep the "ruby" logo. I know that our logo is already quite well known and stuff, but i think since we're trying to let Mendicant University turns into a more inclusive (in a programming languages standpoint) environment to other languages, maybe the Ruby logo don't fit that well anymore.

I don't want it to be read as a nitpicking or something, i just wanted to share this idea i had about this logo discussion. 

Anyway, i think this new logo is a real improvement from the old one.

+1 on that.

**Comment by jordanbyron** [comment]
@fguillen there was an EPS version of the logo in the archive I linked to on the mailing list. That had a transparent background.

@pellegrino: You're probably right that a pull request on University Web isn't the right place to be talking about this. Please send your thoughts to the alumni mailing list and we can discuss it there with the group.

**Comment by fguillen** [comment]
This pull request is not valid anymore. Check the [new one](https://github.com/rmu/university-web/pull/117).

**Comment by jordanbyron** [comment]
@fguillen Just so you know, you didn't have to close this pull request and open a new one. Github is smart and pulled in your new commits.

**Comment by fguillen** [comment]
On Fri, Sep 23, 2011 at 4:04 PM, Jordan Byron
reply@reply.github.com
wrote:

> @fguillen Just so you know, you didn't have to close this pull request and open a new one. Github is smart and pulled in your new commits.

Good to know. Thanks.

f.

## 

Fernando Guillén
Freelance Web Developer
http://www.fernandoguillen.info
http://spainrb.org/fernando-guillen

**Pull request closed without merging**
