### PR TITLE
Rails 3 upgrade

### PR DESCRIPTION
**Pull request by marksim**
All tests pass that passed before the upgrade.  I am looking into the 2 failing tests that seem to be currently checked into rmu/university-web

### CODE REVIEW

**Comment by jordanbyron** [comment]
Hi Mark,

I'm not seeing any failing tests - both in the current version of master and with your patch applied. Which tests are failing for you?

I am however seeing a few problems associated with the new version of rake. When I run the tests I get two warnings:

```

WARNING: Global access to Rake DSL methods is deprecated.  Please include
    ...  Rake::DSL into classes and modules which use the Rake DSL methods.
WARNING: DSL method University::Application#task called at /Users/byron/.rvm/gems/ruby-1.9.2-p0@rmu-university-web/gems/railties-3.0.7/lib/rails/application.rb:215:in `initialize_tasks'
```

Also, this further breaks TestUnit by not displaying each test as a green or red block. We already know there are issues with TestUnit, so this may just be the straw that breaks the camels back. 

Anyway, let me know what tests are failing for you and if you can get those warnings silenced. I'll work on either fixing or replacing TestUnit.

Thanks!

**Comment by jordanbyron** [comment]
@marksim did you get a chance to see which tests are failing for you?

**Comment by marksim** [comment]
Tests failing were because I failed to generate the static site.  My bad.

I'll look at the warnings.

**Comment by jordanbyron** [comment]
That's what I would have guessed. Let me know about those warnings. 

Jordan

**Comment by marksim** [comment]
Warnings Fixed.  Let me know if you need anything else to approve this.

**Comment by jordanbyron** [comment]
Excellent! Your changes are now in the [summer_hits](https://github.com/rmu/university-web/tree/summer_hits) branch and will be merged into master once the July core course ends. Thanks for your work!

**Pull request closed without merging**
