### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by jaimeiniesta**
PublicController tried to use the 'static' layout, that doesn't exist.

### CODE REVIEW

**Comment by jordanbyron** [comment]
The static layout is generated when you run:

```
rake public-site:generate
```

**Comment by jaimeiniesta** [comment]
Sorry!

**Comment by jordanbyron** [comment]
No problem. It probably should say something about that in the README to avoid confusion.

**Comment by jaimeiniesta** [comment]
Generated files should also go in .gitignore, then?

**Comment by jordanbyron** [comment]
Probably. I don't know why I never added them. Probably because I kept changing their names. But things have stabilized so we can add them now.

**Pull request closed without merging**
