### PR TITLE
map enhancements

### PR DESCRIPTION
**Pull request by rubysolo**
Added custom marker icons and popup windows

### CODE REVIEW

**Comment by jordanbyron** [comment]
Hey Solomon,

Thanks for working on these map enhancements. They are really cool, especially the marker icons! I did have a few issues with the code and implementation that I was hoping we could fix:

First, clicking on a marker was rendering really strange for me: http://i.imgur.com/O4OyS.png I'm not sure that matters though because initially when we discussed this feature, I expected this feature to use [Info Windows](http://code.google.com/apis/maps/documentation/javascript/examples/infowindow-simple.html) to display each person's information. 

But now that I've seen your implementation, I think I want something different! I think it would be really cool to have the alumni map at the top of the alumni page. And when an alumni is clicked on the map, is reveals them in the list and grays out the others. What do you think about that? Then we can also add a tiny map icon next to the github icon which when clicked reveals the alumni's location on the map.

I also worry that our User model is really cluttered with maps specific methods and scopes. I was ok when we had one or two, but now we are over 5 and things are getting messy. To simplify, let's exclude staff since the map will be on the alumni page. We should also add a preference to AlumniPreferences for displaying on the map. Feel free to create a presenter class if that is what it takes to keep our User model for bloating with these map specific methods.

I know these are some major changes, but with them I feel like we can have a usable, public facing map.

Thanks! 

Jordan

**Comment by rubysolo** [comment]
Jordan--

Your rendering is really strange -- not sure what's going on there.  Here's
what it looks like on my side:  http://imgur.com/a/NHRAV  I'm building a
custom "info window" and rendering something similar to the alumni partial
into it.  It looks like yours might be displaying the template instead of
rendering into the popup.

I like consolidating the map and index views -- it would simplify the map
data, since we wouldn't need to recreate the entire partial -- probably just
need an id to link to the pre-rendered div. I'll give that a shot when I get
a chance.

Thanks,

Solomon

**Comment by jordanbyron** [comment]
Oh that is really different! Much closer to what I was expecting. Anyway, if you have time to work on the new idea I outlined that would be great.

Thanks!

Jordan

**Comment by jordanbyron** [comment]
Closed due to [new pull request](https://github.com/rmu/university-web/pull/97)

**Pull request closed without merging**
