### PR TITLE
Added 'View my Profile' link to users' dropdown 

### PR DESCRIPTION
**Pull request by pellegrino**
Small UI improvement. Added 'View my Profile' link to users' dropdown to make easier to
visualize their own public information. 

It may seem silly, but i find myself a lot hunting where to find my public profile at uni-web.  :)

### CODE REVIEW

**Comment by jordanbyron** [comment]
Personally, I'm not crazy about the way it looks with "View my Profile" right above "Edit Profile".  At a bare minimum, can you remove "my" from the link so it just reads, "View Profile". 

Thanks!

Jordan

**Comment by pellegrino** [comment]
Oh, okay. So you think that removing that "my", it would be interesting to merge?  If you believe its something that worth doing, i'll do it right away. 
Thanks!

**Comment by jordanbyron** [comment]
Yeah I should have just made this change myself and merged it in. Sorry I was on a roll closing pull requests yesterday. I'll make that change. Thanks again for your work!

Jordan

**Comment by pellegrino** [comment]
Just did at my repo. :) 
How can i resubmit the pull request?  I can't see that commit listed here.

**Comment by jordanbyron** [comment]
I think if you just go into your fork and do another pull request it will either update this pull request or create another.

**Comment by pellegrino** [comment]
Well.. just did it. It should do the trick.

**Comment by jordanbyron** [comment]
Merged and deployed. Thanks so much!

**Pull request merged**
