### PR TITLE
new login logo without letters nor circle (II)

### PR DESCRIPTION
**Pull request by fguillen**
Check the [screenshot](http://dl.dropbox.com/u/1488231/tmp/login_screenshot.png)

### CODE REVIEW

**Comment by jordanbyron** [comment]
Merged and deployed. Thanks for working on this!

**Comment by semmons99** [comment]
Can we get a higher res version of the png on the login page? It's pretty jagged on my screen.

**Comment by fguillen** [comment]
On Sat, Sep 24, 2011 at 4:21 PM, Shane Emmons
reply@reply.github.com
wrote:

> Can we get a higher res version of the png on the login page? It's pretty jagged on my screen.

Shane, can I have an screenshot or something of how the image show for you?

I'm attaching what I see. I looks good for me, I don't know.

f.

## 

Fernando Guillén
Freelance Web Developer
http://www.fernandoguillen.info
http://spainrb.org/fernando-guillen

**Comment by semmons99** [comment]
http://imageshack.us/photo/my-images/20/screenshot20110924at947.png/

**Comment by fguillen** [comment]
On Sun, Sep 25, 2011 at 3:51 AM, Shane Emmons
reply@reply.github.com
wrote:

> http://imageshack.us/photo/my-images/20/screenshot20110924at947.png/

I can't reproduce this bad rendering.

I have tried with:
- Chrome
- Safari
- Firefox

On OS X

Which browser are you using?

How do you see this image out of the browser?:
- http://university.rubymendicant.com/images/MU_logo_no_letters_no_circle_300.png

f.

## 

Fernando Guillén
Freelance Web Developer
http://www.fernandoguillen.info
http://spainrb.org/fernando-guillen

**Comment by semmons99** [comment]
That image has the same jagged look on my browser. It's Chrome for OS X version 16.0.889.9. I did just check on Safari now that you mentioned it looks fine elsewhere and it appears fine. I'm going to assume this is a rendering issue for Chrome.

**Pull request merged**
