### PR TITLE
Full Text search in Courses.

### PR DESCRIPTION
**Pull request by Nerian**
### Brief Summary:

Mendicant Core Skill Course s9. 

Within a given course, have a search box which will search all course resources. including:
- Course Description, Notes
- Assignment Descriptions, Notes
- Submission Descriptions, Comments
- Course IRC log

@jordanbyron: A couple of questions.

I have the search part working on the console and a simple CourseController#Search action. 

I have created the tests but when I run `rake test` they seem to not fail. Check `test/integration/courses/search_test`. They are mostly in pending status, but the first one should fail. Yet, it does not fail when I run `rake test`, not sure why. Can you point me in the right direction?

How would you like the view? Checkout `views/courses/search`. Right now it just shows the contents of the result array.

### CODE REVIEW

**Comment by jordanbyron** [comment]
> I have created the tests but when I run rake test they seem to not fail. Check test/integration/courses/search_test. They are mostly in pending status, but the first one should fail. Yet, it does not fail when I run rake test, not sure why. Can you point me in the right direction?

If you look at the test results for that file `rake test:integration TEST=test/integration/courses/search_test.rb` you'll see no tests are being run at all. The problem is that you've wrapped the entire test in a `describe` block which, if you look at the other tests, we don't use. The `describe` helper is from MiniTest::Spec, which we are not using in this project. Instead we are using something similar to [Contest](https://github.com/rmu/university-web/blob/master/test/support/mini_contest.rb) which uses a helper called `context`.

---

`views/courses/search` is a good start. Here are a few things that would be ideal to have:
- Highlight search term in results (using the `highlight` helper)
- Render the results in the `#search.bucket` div. If you change the `views/courses/search.html.haml` file into a partial and sprinkle in a little javascript that should be fairly painless.

---

The other large problem is that all the search code is located in the controller. As a general rule of thumb controller code should be very short and not contain business logic. Try to push that back down into the Course model.

Any questions just let me know. Thanks for working on this!

**Comment by Nerian** [comment]
Check the new view. It is simpler.

I moved the search code to a helper in applicationHelpers

Alas, my javascript abilities are near nil :) 

I moved all the code of the search view into a partial, but I am not sure how can I achieve that the search results get inside of #search.bucket. The rendering of the #show view needs a lot of variables. Should I copy/paste the code in #show so that those variables are available there? Doesn't seem like a good way :)

**Comment by jordanbyron** [comment]
@Nerian I think we've regressed a bit. Here are my concerns:

### ApplicationController#search_course_resources

As I mentioned before, controller code should be very short and not contain business logic. All you've done here is move that search logic from one controller (CoursesController) to every controller! Remember that any method on ApplicationController is inherited by all other controllers. Definitely not what we want to do. As I mentioned before, instead we want to push that code down to the Course model. 

### lib/result.rb / View refactor

I think the idea of the `lib/result.rb` is interesting, but there are several problems with it.

The name is very generic and doesn't do a good job explaining what it is. A better name would be CourseSearchResult or even just SearchResult. Also you should put files like that in /app/models. 

The bigger problem is that now the view / logic code is mixed together. `search_course_resources` is returning not just model data, but link information as well. View / presentation data should no creep up into the model layer (which is were the search code belongs).

### Displaying results with javascript

You'll want to create a file called `app/views/courses/search.js.erb` and make sure `CoursesController#search` looks something like this:

``` ruby

def search

  @results = @course.search(params[:search])

  respond_to do |format|
    format.js
  end
end
```

Move everything from line 8 down in `app/views/courses/_search` into `app/views/courses/_search_results.html.haml`. That file will look like this:

``` haml
- if @search.empty?
  %h1 No matches found
- else
  %ul
    - @results.each do |result|
      %li
        = link_to("#{result.description}", result.link) unless result.link.nil?
        = ("#{result.description}" + result.content) unless result.content.nil?
```

Then make sure at the bottom of `app/views/courses/_search.html.haml` you have an empty div called `search-results`

Lastly, in `search.js.erb` you'll render the search partial and replace the contents of #search-results:

``` js
var results = "<%= escape_javascript(render(:partial => 'search_results')) %>";
$('#search-results').html(results);
```

I'm not sure if you've used Erb before, but the stuff between the <% %> tags is ruby code. That will create a javascript string variable called `results` which will have the rendered html code from the `search_results` partial. Then all we do is replace the html code inside `<div id='search-results'>` with the partial code.

---

Hopefully this is enough to get you back on track. Please let me know if anything is unclear and thanks again for your help with this!

**Comment by Nerian** [comment]
@Jordanbyron

Thanks a lot for the input!

I get a 406 error code when I do the search and nothing is rendered. It seems that the browser doesn't expect javascript. I am not sure where the error is. O-o

**Comment by jordanbyron** [comment]
Make sure you add the `:remote => true` option to the search form. That will perform an ajax request and fix the 406 error.

**Comment by Nerian** [comment]
@jordanbyron

Nice :)  Now it works like a charm. 

I added highlighting to `description` and `shared notes` matches.

I will implement now the tests.

**Comment by Nerian** [comment]
@jordanbyron

I have got this test:

``` ruby
        test "I don't get result if there is no match" do
          visit course_path(@course, :anchor => "search")
          fill_in 'search', with: 'blablabla'
          click_button('Search')
          assert_content 'No matches found'
        end
```

But the assertion is failing because , I think, is checking the assertion before the ajax call actually finish.

How can I make it wait a little bit?

**Comment by Nerian** [comment]
@jordanbyron

Unit Tests provided. What do we do with integration tests?

**Comment by jordanbyron** [comment]
Thanks to the hard work of @ptn this feature is finally ready to be merged into master. Thanks @Nerian for laying the groundwork and doing a lot of the heavy lifting to bring full text search to university web!

**Pull request closed without merging**
