### PR TITLE
integrated github with the submissions page

### PR DESCRIPTION
**Pull request by seejee**
Jordan,

This is the work I did for my community service RbMU project. In short, a student associates a submission with a github repo, and then commits to that repo will show up as activities in the submissions page and the activity log.

This is my first production rails work, and I am extremely novice when it comes to HTML/JS/CSS so I don't mind you being extra hard on me before accepting this pull request. :)

To get it set up a few things need to happen:
- Create  config/github.yml from config/github.yml.example. In order to pull commits from an rmu repo, I need to use the api token of an rmu user to query github. My personal account works great, but I would anticipate that in production the rmu user's api token would be used.
- It would be a bad idea to query github on every submission page view, so I designed commits to be populated via an  offline query of github to download any new commits since the last query. I created a rake task called github:check_for_new_commits that I intend to be run in a cron job a few times an hour to populate the u-web db with the github commit information.

Please let me know if you have any questions or concerns. Kudos to you for creating a rails app that a rails newbie could contribute to quickly!

-cg

### CODE REVIEW

**Comment by seejee** [comment]
Hi Jordan,

Since it's been about 10 days since I submitted this pull request, would you prefer I merged in my changes with the latest rmu-university on my end and created a new pull request?

Thanks!
-cg

**Comment by jordanbyron** [comment]
Hi Chris,

Sure if you wouldn't mind that would make reviewing your pull request much easier. Sorry it has sat here so long. I'll try my best to review this again today.

Thanks!

Jordan

**Comment by seejee** [comment]
No problem! I know you're a busy, busy man. :) I'll get it merged tonight after work and send another pull request.

Thanks!

-cg

**Comment by seejee** [comment]
Jordan,

I rebased onto the latest university-web commit and resubmitted my pull request. Let me know if you'd like me to improve anything.

Thanks!

-cg

**Comment by jordanbyron** [comment]
This is a really neat feature, but we do need to do some work before it can be merged:
- Clicking the commit on the submission page should expand the full description which should have a link to the commit on github as well as the SHA hash of the commit
- Rather than display times in UTC, use the logged in user's local timezone (Remove .utc)
- Instead of the time, display the SHA hash in GithubCommit#to_s
- When updating Submission#github_repository, the associated controller action should render the link. Look at `Courses::Assignments::SubmissionsController#description` and  `app/views/courses/assignments/submissions/description.text.erb` for an example.
- The github_repository field didn't do a very good job indicating it expected the repos name. At first I put the full URL of the project. 
- Additionally, the github_repository field is right on top of the description field. Some spacing and visual separation is needed here.
- With all the commits inline, the submission page is starting to get visually cluttered. Can you try playing around with the background color of the github commits so that are visually distinct from the other activities.
- I'd also commits to roll up like updates to the description do. In that case if there were 2 consecutive commits to github, the submission page would show the first, and then a link below "Display 1 more like this.". See `ActivityHelper#group_by_description` for a really crappy example of how to do that.

I did start on some of this stuff, including moving your code from lib to app/models. Pull in those changes from the [geihsler-github-submissions branch](https://github.com/rmu/university-web/tree/geihsler-github-submissions) and let me know if you need help with these changes.

Thanks again!

Jordan

**Comment by seejee** [comment]
Thanks for the feedback! Those are all great suggestions. I'll work on it this weekend and ping you on IRC if I have any trouble.

-cg

**Comment by seejee** [comment]
Hi Jordan,

I think I've addressed everything on your list, with the exeption of the first item:
- I'm using the activity model to store the commits, and I don't see a way to store individual pieces of information (like SHA, github commit date) within them. So I think I would have to make GithubCommit a proper model, and duplicate some of the activity presentation logic to render a link for each commit. Please let me know if you see a better way.

As for the changes, I have a few questions/comments:
- I refactored (and added tests for) the activity grouping logic. At the moment, I have the ActivityGrouper class in the same file as ActivityHelper. Is this appropriate? Where should it live?
- The repository entry field will now accept either the full URL or just the repo name. I added a message on the screen stating that as well.

Please let me know if there is anything else that I can improve.

Thanks again!

-cg

**Comment by jordanbyron** [comment]
Awesome. To answer your questions:

> I'm using the activity model to store the commits, and I don't see a way to store individual pieces of information (like SHA, github commit date) within them.

I don't know if this is a problem. We just need that data to be in `GithubCommit` so when it is passed to `Assignment::Submission#add_github_commit` we can construct the description which will then include the SHA hash and GH commit date. Once those are written out to the activity we never need to pull them again.

> I refactored (and added tests for) the activity grouping logic. At the moment, I have the ActivityGrouper class in the same file as ActivityHelper. Is this appropriate? Where should it live?

That should be in its own file and live in /app/models.

---

Again really nice work on this. I haven't pulled it down to check it out, but once you make these final tweaks it should be close enough that I will be able to merge this monster of a feature.

Thanks again Chris!

Jordan

**Comment by seejee** [comment]
Thanks. Don't pull yet. I broke the expansion of the activities. I'll address these issues tonight.

-cg

**Comment by seejee** [comment]
Ok Jordan, I think I've finally got it all working!

A github link to the commit is displayed if you click and expand the github commit, and all the github commits have a github blue gradient background.

Please take a look when you get a chance.

Thanks!
-cg

**Comment by jordanbyron** [comment]
Chris,

It's in! This was a bear of a commit and while there are a few bits I'd like to cleanup (Parsing the description for the commit ID, not loading the repo name when clicking edit, etc) this is good enough to get merged in.

If you can, I'd love to have some explanation of our github integration in the README. If you get a chance write something up and shoot over a pull request.

Thanks again! And feel free to hack on some more features if you'd like.

Jordan

**Comment by seejee** [comment]
Jordan,

I'll definitely write up the README. I agree that parsing the description is a little hacky, but I couldn't think of any other way to get the SHA while still using the Activity model to store the commit data. If it gets any more complex then I think the commits might warrant their own model. If you have any specific suggestions to improve it, I'd be happy to keep working on it.

I saw that you had to do a little more cleanup while merging it in. Sorry it wasn't a little cleaner. This was my first rails work ever, and I rarely do any webdev so thanks for being patient!

-cg

**Pull request closed without merging**
